### ISSUE TITLE
StatusCode OK on connection problems

### ISSUE THREAD

**Issue by ihoff** [tideland/gocouch#22]
Hi,
we just found an irritating status code 200 when the couchDB service is not available.

Maybe the resultSet.statusCode better should be initialized with 0 [here](https://github.com/tideland/gocouch/blob/master/couchdb/resultset.go#L100)

**Comment by ihoff** [comment]
Can be reproduced like this:
1. Stop couchDB server or set an invalid host configuration in _cfg_.
2. Execute something like this:
```go
cdb, err := couchdb.OpenPath(cfg,"test-db")
if err == nil {
  result := cdb.DeleteDatabase()
  if result.StatusCode() == 200 {
    fmt.PrintLn("Here we go...")
  }
}
```

**Comment by themue** [comment]
Added better mapping of errors to status codes.
